### ISSUE TITLE
Test is failed

### ISSUE THREAD

**Issue by noboru-i** [kazy1991/danger-findbugs#4]
I try to execute `bundle exec rake spec` locally, I had error.

```
Failures:

  1) Danger::DangerFindbugs with Dangerfile Create bug issues
     Failure/Error: expect(@my_plugin.bug_issues).not_to be_nil

     NoMethodError:
       undefined method `bug_issues' for #<Danger::Dangerfile:0x007fd8e5b0f6d8>
     # ./vendor/bundle/ruby/2.4.0/gems/danger-5.2.1/lib/danger/danger_core/dangerfile.rb:68:in `method_missing'
     # ./vendor/bundle/ruby/2.4.0/gems/danger-5.2.1/lib/danger/plugin_support/plugin.rb:23:in `method_missing'
     # ./spec/findbugs_spec.rb:48:in `block (3 levels) in <module:Danger>'

  2) Danger::DangerFindbugs with Dangerfile Send inline comments
     Failure/Error: expect(@my_plugin.send_inline_comment).not_to be_nil

     NoMethodError:
       undefined method `send_inline_comment' for #<Danger::Dangerfile:0x007fd8e5937cc0>
     # ./vendor/bundle/ruby/2.4.0/gems/danger-5.2.1/lib/danger/danger_core/dangerfile.rb:68:in `method_missing'
     # ./vendor/bundle/ruby/2.4.0/gems/danger-5.2.1/lib/danger/plugin_support/plugin.rb:23:in `method_missing'
     # ./spec/findbugs_spec.rb:55:in `block (3 levels) in <module:Danger>'

Deprecation Warnings:

Using `any_instance` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/ishikuranoboru/.ghq/github.com/noboru-i/danger-findbugs/spec/findbugs_spec.rb:52:in `block (3 levels) in <module:Danger>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Finished in 0.11623 seconds (files took 0.51359 seconds to load)
9 examples, 2 failures
```

I think, https://github.com/kazy1991/danger-findbugs/pull/3/files#diff-cb2124f377a7bb77eca4ecd8a4c0db42R77 changes makes `bug_issues` and `send_inline_comment` private, So we cannot call these methods by outside.

How about remove these test code?

**Comment by kazy1991** [comment]
@noboru-i 
Thanks for reporting on the issue 
Check it later, ASAP 👍
